version: '3'
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_FILTER=status=running
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "9998:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    tty: true
    stdin_open: true

  filemanager:
    container_name: filemanager
    image: tigerdockermediocore/tinyfilemanager-docker:2.4.3
    ports:
      - "9997:80"

  # なんかdownで止まる... sudo service docker restart しないといけなくなる
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:5140
        tag: "docker.{{.Name}}"
    depends_on:
      - fluentd

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=Japan"
      - xpack.security.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
    image: kibana:8.11.3
    environment:
      - "TZ=Japan"
    ports:
      - "5601:5601"

  fluentd:
    container_name: fluentd
    build:
      context: .
      target: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/logs:/fluentd/log
    ports:
      - "5140:5140"
      - "5140:5140/udp"
    links:
      - "elasticsearch"

volumes:
  es-data:
    driver: local
